name: build-apps
on:
  push:
    branches:
      - 'v2' # @TODO: change branch to master after release of v2
jobs:
  android_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
      - run: npm install
      - run: npm run build:android

      # Upload the APK to the build number folder
      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: 'android/app/build/outputs/apk/release/app-release.apk'
          destination-dir: '/'
          bucket-root: ${{ format('/webview/react-native/android/build.{0}', github.run_number) }}

      # Upload the APK to latest folder overriding the previous APK
      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: 'android/app/build/outputs/apk/release/app-release.apk'
          destination-dir: '/'
          bucket-root: '/webview/react-native/android/latest'


  ios_build:
    if: false # disable iOS builds until we have a valid Apple Developer account
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build:ios

      # Upload the IPA to the build number folder
      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: 'android/app/build/outputs/apk/release/app-release.apk'
          destination-dir: '/'
          bucket-root: ${{ format('/webview/react-native/ios/build.{0}', github.run_number) }}

      # Upload the IPA to latest folder overriding the previous IPA
      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: '' # @TODO: get the IPA file path
          destination-dir: '/'
          bucket-root: '/webview/react-native/ios/latest'
