name: build-android-app
on:
  push:
    branches:
      - 'v2' # @TODO: change branch to master after release of v2
jobs:
  android_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
      - run: npm install
      - run: npm run build:android

      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: 'android/app/build/outputs/apk/release/app-release.apk'
          output-file-url: 'true'
          destination-dir: '/'

      - name: Print file URL
        run: echo '${{ steps.upload.outputs.file-url }}'

      - name: Print file QR code
        run: echo '${{ steps.upload.outputs.file-url }}' > file-url.txt

  ios_build:
    if: false # disable iOS builds until we have a valid Apple Developer account
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build:ios

      - uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: ios/build/Build/Products/Release-iphoneos/ExpoKitApp.app
