name: build-ios-app
on:
  push:
    branches:
      - 'v2' # @TODO: change branch to master after release of v2
jobs:
  build:
    if: false # disable iOS builds until we have a valid Apple Developer account
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: fastlane ios build_ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
